apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: kube-buding-system
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buding-system
  namespace: kube-buding-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buding-system-ns-secrets-manager
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - secrets
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: buding-system-ns-secrets-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: buding-system-ns-secrets-manager
subjects:
  - kind: ServiceAccount
    name: buding-system
    namespace: kube-buding-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buding-kube
  namespace: kube-buding-system
  labels:
    app: buding-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buding-kube
  template:
    metadata:
      labels:
        app: buding-kube
    spec:
      serviceAccountName: buding-system
      containers:
      - name: buding-kube
        image: buding-kube:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: KUBE_RUNTIME_ENV
          value: "KUBE_POD"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: buding-kube-service
  namespace: kube-buding-system
  labels:
    app: buding-kube
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: buding-kube